<?php

namespace AppBundle\Repository;

/**
 * FicheTechRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FicheTechRepository extends \Doctrine\ORM\EntityRepository
{
}
